name: flutter_savdogar
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  permission_handler:
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.5.1
  flex_color_scheme: ^7.3.1
  easy_date_timeline: ^1.1.3
  fl_chart: ^0.69.0
  http: ^1.2.2
  mime: ^2.0.0
  http_parser: ^4.0.2
  flutter_spinkit: ^5.2.1
  flutter_slidable: ^3.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
